// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Updated to use the try1 database
const SUPABASE_URL = "https://odovhhyrenqeauiwlcxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kb3ZoaHlyZW5xZWF1aXdsY3h5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1MjU2MjgsImV4cCI6MjA1NzEwMTYyOH0.oK2-LgxGwvjI56wY2MFAebgkV_DUYoc6D9B45SgZsWo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);